# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for pygsbox single-file executable."""

a = Analysis(
    ['pygsbox/cli.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('pygsbox/PROGRESS.json', 'pygsbox'),
        ('pygsbox/README.md', 'pygsbox'),
        ('pygsbox/requirements.txt', 'pygsbox'),
    ],
    hiddenimports=[
        'numpy',
        'Pillow',
        'zstandard',
        'scipy',
        'pygsbox.common',
        'pygsbox.common.codec',
        'pygsbox.common.compress',
        'pygsbox.common.file_utils',
        'pygsbox.common.version',
        'pygsbox.common.progress',
        'pygsbox.common.freq',
        'pygsbox.core',
        'pygsbox.core.splat_data',
        'pygsbox.core.morton',
        'pygsbox.core.transform',
        'pygsbox.core.sh_rotation',
        'pygsbox.formats',
        'pygsbox.formats.ply',
        'pygsbox.formats.splat',
        'pygsbox.formats.spx',
        'pygsbox.formats.spz',
        'pygsbox.formats.sog',
        'pygsbox.formats.ksplat',
        'pygsbox.formats.glb',
        'pygsbox.formats.obj',
        'pygsbox.advanced',
        'pygsbox.advanced.kmeans',
        'pygsbox.advanced.simplify',
        'pygsbox.advanced.lod',
        'pygsbox.advanced.autocut',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='pygsbox',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
